// Code generated by logcopter-gen; DO NOT EDIT.

package indices

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.escuse-me.cmd.escuse-me.cmds.indices")
